name: OCI Resource Model Source
version: 1.0
rundeckPluginVersion: 1.0
author: psadmin.io
date: 10/13/2020
url: psadmin.io
providers:
    - name: OCI-Resource-Model-Source
      service: ResourceModelSource
      plugin-type: script
      script-interpreter: python3
      script-file: nodes.py
      resource-format: resourcejson
      config:
        - type: String
          name: compartment_desc
          title: Compartment Description
          description: Description of Compartment
        - type: String
          name: compartment
          title: Compartment ID
          description: Enter the Compartment ID that contains the Nodes.
          required: true
        - type: String
          name: node_user
          title: Default OCI Node User
          description: Enter the default user to use when connecting to OCI Nodes
          default: opc
        - type: String
          name: oci_config
          title: OCI Configuration File
          description: Enter the OCI Configuration File location. Leave blank to use Instance Principal. (optional)
        - type: String
          name: vnic_tag
          title: VNIC Override Tag
          description: Enter a freeform Tag Key that will specify which VNIC Rundeck should connect to. If not specified or a VNIC is not found with this Tag, the primary VNIC will be used. (optional)
        - type: String
          name: defined_tags
          title: OCI Defined Tag Namespaces
          description: Enter a comma seperated list of OCI Defined Tag Namespaces to be included in Tag Value mapping to Rundeck Nodes. (optional)
        - type: String
          name: attribute_namespace
          title: Attributes Tag Namespace
          description: OCI Tag Namespace to add attributes to nodes. Default is `rundeck`
          default: rundeck
        - type: Boolean
          name: freeform_tags
          title: OCI Freeform Tag Values
          description: Enable OCI Freeform Tag Value mapping to Rundeck Nodes. (optional)

